name: Release

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths-ignore:
      - README.md

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --save-dev semantic-release@23 @semantic-release/changelog@6 @semantic-release/git@10 @semantic-release/exec@6 conventional-changelog-conventionalcommits@7

      - name: Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release@23.0.7
